name: psalm

on:
  push:
    paths:
      - '**.php'
      - '.github/**.yml'
      - '.github/**.yaml'
      - '*.xml'
      - '*.xml.dist'

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install --prefer-dist --ansi --no-interaction --ansi -v

#      - name: Install global psalm
#        run: composer global require vimeo/psalm --prefer-dist --ansi --no-interaction --no-scripts

      - name: Run psalm
        run: composer psalm
